version: '3.9'

services:
  web:
    build:
      context: .
      target: dev
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
      - /app/.vscode
      - /app/.angular

  caddy:
    image: caddy:2.8-alpine
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - ./dist/adventrame/browser:/var/www/html
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "8085:80"
    depends_on:
      - web

